spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db?serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto:  none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    session:
      timeout: 1800 #초 기반 (기본)1800 = 30분, 분 기반 90m
